language:	python
python:
- "3.6.2"
# command to install dependencies
install:
- pip install codecov
script:
- python factorial.py
- coverage run factorial.py
after success:
- bash <(curl -s https://codecov.io/bash)
