language:	python
python:
- "3.6.2"
# command to install dependencies
install:
- pip install codecov
script:
- python factorial.py
- coverage run factorial.py
after success:
- codecov --token=98d33542-efb7-4048-885f-deeddf4cc42d
